USE fictionalTtrpgParty;
GO;
ALTER TABLE Characters WITH CHECK
ADD CONSTRAINT FK_Level FOREIGN KEY(Level) REFERENCES Level(ID)
ON UPDATE CASCADE
GO
ALTER TABLE CharacterClass WITH CHECK
ADD CONSTRAINT FK_CharacterID FOREIGN KEY(CharacterID) REFERENCES Characters(CharacterID)
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE CharacterClass WITH CHECK
ADD CONSTRAINT FK_ClassID FOREIGN KEY(ClassID) REFERENCES Class(ID)
ON UPDATE CASCADE
GO
ALTER TABLE Vendors WITH CHECK
ADD CONSTRAINT FK_Town FOREIGN KEY(Town) REFERENCES Towns(ID)
ON UPDATE CASCADE
GO
ALTER TABLE Acquisitions WITH CHECK
ADD CONSTRAINT FK_AcqCharacterID FOREIGN KEY(CharacterID) REFERENCES Characters(CharacterID)
ON UPDATE CASCADE
GO
ALTER TABLE Acquisitions WITH CHECK
ADD CONSTRAINT FK_ArtifactID FOREIGN KEY(ArtifactID) REFERENCES Artifacts(ID)
ON UPDATE CASCADE
GO
ALTER TABLE Artifacts WITH CHECK
ADD CONSTRAINT FK_VendorID FOREIGN KEY(VendorID) REFERENCES Vendors(VendorID)
ON UPDATE CASCADE
GO
ALTER TABLE CharacterXP WITH CHECK
ADD CONSTRAINT FK_XPCharacterID FOREIGN KEY(CharacterID) REFERENCES Characters(CharacterID)
ON UPDATE CASCADE
GO
ALTER TABLE CharacterXP WITH CHECK
ADD CONSTRAINT FK_XPID FOREIGN KEY(XPID) REFERENCES XP(ID)
ON UPDATE CASCADE
GO